export const workData = [
    {
        workName: "Work Name 1",
        workDescription: "This work is auto-generated by Google. Find out more !",
        workImageUrl: ""
    },
    {
        workName: "Work Name 2",
        workDescription: "This work is auto-generated by Google. Find out more !",
        workImageUrl: ""
    },
    {
        workName: "Work Name 3",
        workDescription: "This work is auto-generated by Google. Find out more !",
        workImageUrl: ""
    },
    {
        workName: "Work Name 4",
        workDescription: "This work is auto-generated by Google. Find out more !",
        workImageUrl: ""
    }
]